<?php

$posts = App\config\DB::posts();

//print_r($posts);
?>

<div class="cards">
    <?php foreach ($posts as $post) :?>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <?= $post['title'] ?>
                </h5>
                <p class="card-body">
                    <?= $post['body'] ?>
                </p>
                <a href="post/show/<?= $post['id']; ?>" class="link">Read more</a>
            </div>
        </div>
    <?php endforeach; ?>
</div>