<?php

$errors = [];
$messages = [];

// Если файл был отправлен
if (!empty($_FILES)) {

    // Проходим в цикле по файлам
    for ($i = 0; $i < count($_FILES['files']['name']); $i++) {

        $fileName = $_FILES['files']['name'][$i];

        // Проверяем размер
        if ($_FILES['files']['size'][$i] > UPLOAD_MAX_SIZE) {
            $errors[] = 'File size unacceptable ' . $fileName;
            continue;
        }

        // Проверяем формат
        if (!in_array($_FILES['files']['type'][$i], ALLOWED_TYPES)) {
            $errors[] = 'File format unacceptable ' . $fileName;
            continue;
        }

        $filePath = UPLOAD_DIR . '/' . $_SESSION['id'] . '/' . basename($fileName);

        // Пытаемся загрузить файл
        if (!move_uploaded_file($_FILES['files']['tmp_name'][$i], $filePath)) {
            $errors[] = 'Upload file error ' . $fileName;
            continue;
        }
    }

    if (empty($errors)) {
        $messages[] = 'Files were uploaded';
    }

}

// Если файл был удален
if (!empty($_POST['name'])) {

    $filePath = UPLOAD_DIR . $_SESSION['id'] . DIRECTORY_SEPARATOR . $_POST['name'];
    $commentPath = COMMENT_DIR . $_SESSION['id'] .  $_POST['name'] . '.txt';

    // Удаляем изображение
    unlink($filePath);

    // Удаляем файл комментариев, если он существует
    if(file_exists($commentPath)) {
        unlink($commentPath);
    }

    $messages[] = 'File removed';
}

if(isset($_SESSION['id'])){
    // Получаем список файлов, исключаем системные
    $files = scandir(UPLOAD_DIR . DIRECTORY_SEPARATOR . $_SESSION['id']);
    $files = array_filter($files, function ($file) {
        return !in_array($file, ['.', '..', '.gitkeep']);
    });
}


?>

<? if(isset($_SESSION['id'])){ ?>
<h1 class="mb-4">Upload a new one</h1>
<div class="container pt-4">

    <!-- Вывод сообщений об успехе/ошибке -->
    <?php foreach ($errors as $error): ?>
        <div class="alert alert-danger"><?=$error; ?></div>
    <?php endforeach; ?>

    <?php foreach ($messages as $message): ?>
        <div class="alert alert-success"><?=$message; ?></div>
    <?php endforeach; ?>

    <h2>File list</h2>

    <!-- Вывод изображений -->
    <div class="mb-4">
        <?php if (!empty($files)): ?>
            <div class="row">
                <?php foreach ($files as $file): ?>

                    <div class="col-12 col-sm-3 mb-4">
                        <form method="post">
                            <input type="hidden" name="name" value="<?=$file; ?>">
                            <button type="submit" class="close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </form>
                        <a href="<?php echo URL . '/gallery/show/?name=' . $_SESSION['id'].$file; ?>" title="View entire image">
                            <img src="<?php echo URL.'/public/uploads/'.$_SESSION['id'].'/'.$file ?>" class="img-thumbnail"
                                 alt="<?php echo $file; ?>">
                        </a>
                    </div>
 
                <?php endforeach; ?>
            </div><!-- /.row -->
        <?php else: ?>
            <div class="alert alert-secondary">No images uploaded yet &#128530;</div>
        <?php endif; ?>
    </div>


    <!-- Форма загрузки файлов -->
    <form method="post" enctype="multipart/form-data">
        <div class="custom-file">
            <input type="file" class="custom-file-input" name="files[]" id="customFile" multiple required>
            <label class="custom-file-label" for="customFile" data-browse="Choose">Choose your files to upload</label>
            <small class="form-text text-muted">
                Maximum file size: <?php echo UPLOAD_MAX_SIZE / 1000000; ?>Mb.
                Accepted formats: <?php echo implode(', ', ALLOWED_TYPES) ?>.
            </small>
        </div>
        <hr>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div><!-- /.container -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input@1.3.4/dist/bs-custom-file-input.min.js"></script>
<script>
    $(() => {
        bsCustomFileInput.init();
    });
</script>

<? }else{ ?>
<h2>Log in to upload files</h2>
<p>Being <a href="/user/login" >logged in</a> is crucial for operation, including files upload</p>
<? } ?>